# Generated by Django 3.0.7 on 2020-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesInfo',
            fields=[
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('language', models.TextField()),
                ('genre_ids', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('vote_average', models.IntegerField()),
                ('overview', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('movie_ids', models.CharField(max_length=100)),
            ],
        ),
    ]
