# Generated by Django 3.0.7 on 2020-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserList',
        ),
        migrations.AddField(
            model_name='moviesinfo',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='genre_ids',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='overview',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='poster_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='vote_average',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
