# Generated by Django 3.0.7 on 2020-06-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0003_watchedlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesinfo',
            old_name='genre_ids',
            new_name='genres',
        ),
    ]
