# Generated by Django 3.0.7 on 2020-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfapp', '0004_auto_20200627_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedlist',
            name='movie_ids',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
